### ISSUE TITLE
Popup a window on clicking a project under project tab

### ISSUE THREAD

**Issue by 0xPrateek** [0xPrateek/Portfolio-Template#7]
On clicking on any project under Project Tab i want that a window should pop up which consist of :
 - Project Name
 - Project Description
 - Project Links
 - Language Used

**Comment by vaibhav-sharma-frontend** [comment]
hey, @0xPrateek can u assign me this issue?

**Comment by 0xPrateek** [comment]
I am assigning you this issue. I hope you are clear about what we want to be done. Please make sure to update your work after getting assigned so that we can confirm that you are working on it.

**Comment by vaibhav-sharma-frontend** [comment]
@0xPrateek sure

**Comment by vaibhav-sharma-frontend** [comment]
@0xPrateek plz assign this issue to someone else

**Comment by 0xPrateek** [comment]
Okay..!
