### ISSUE TITLE
Project layout

### ISSUE THREAD

**Issue by vaibhav-sharma-frontend** [0xPrateek/Portfolio-Template#9]
In the project section of HTML currently, the table tag is used for layout the various projects. So use divs and nested divs instead of table tag and use proper layout styling (either CSS flexbox or CSS grid) to layout them properly.

For reference regarding grid: https://css-tricks.com/snippets/css/complete-guide-grid/

![table](https://user-images.githubusercontent.com/31318828/70346431-563fe880-1884-11ea-83c9-6ca6ddd1d105.png)

**Comment by vaibhav-sharma-frontend** [comment]
@0xPrateek what's your opinion on this?

**Comment by 0xPrateek** [comment]
Its a scope of improvement.
Are you working on it ? . I'll assign it on this issue

**Comment by vaibhav-sharma-frontend** [comment]
@0xPrateek yes plz assign this issue to me

**Comment by 0xPrateek** [comment]
Sounds Good..! @vsharma20v I am assigning you this issue. Make sure that you update your work by commenting here.
